### ISSUE TITLE
Overzealous auto-complete

### ISSUE THREAD

**Issue by gingerbeardman** [seanosullivanuk/nova-markdownclips#2]
Why is this auto-complete happening?

I had just added the word "so"

![Screen shot 2023-12-02 at 14 09 05](https://github.com/seanosullivanuk/nova-markdownclips/assets/49612/dc7581df-9b55-4eae-acd3-a1670f0f7098)

**Comment by seanosullivanuk** [comment]
Hi there.

Firstly, thank you for using Markdown Clips. 

In regards to your issue, when you begin to type a word Nova does a fuzzy search on the Clip names from left to right. You typed SO and those letters appear in both 'Single line blockquote' and 'strikethrough'.

The way Nova performs this fuzzy search with Clips isn't behaviour I can change I'm afraid. (At least not that I'm aware of). 

Many thanks,
Sean

**Comment by gingerbeardman** [comment]
No worries, I solved it by uninstalling your extension :)

**Comment by seanosullivanuk** [comment]
Sorry to hear it didn't work out for you at this time.

You can tell Nova to stop suggesting Clips as you type, but you'd have to rely on using the Sidebar for insertion. 
<img width="596" alt="Screenshot 2023-12-23 at 14 30 36" src="https://github.com/seanosullivanuk/nova-markdownclips/assets/43788745/19d7396d-d4aa-4206-aef8-a98ce2e9b794">

**Comment by gingerbeardman** [comment]
For me auto-complete has to be whilst typing, otherwise it's no quicker.

But if I can't type English in a markdown file without your autocorrect snippets triggering, then it feels like a problem with their design. 

When I create my own shortcuts in macOS I do it in a way that doesn't clash with typing normal English. I do this by adding a prefix. So i can type, say, #pass to get my passport number but i can still type the word pass and it will not trigger the text expansion.
